### ISSUE TITLE
Pools List view: EC pool should not have Replicas and should show k+m values instead

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#243] opened 2017-04-11 02:24 UTC

**Comment by cloudbehl** [comment] 2017-04-12 08:28
duplicate of #237

**Comment by cloudbehl** [comment] 2017-04-17 12:30
@Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by nthomas-redhat** [comment] 2017-04-26 10:54
Closing the issue as the fix is available

**Closed by nthomas-redhat** 2017-04-26 10:54 UTC
Labels: ux-feedback
