### ISSUE TITLE
When user logs out, tendrl ui continues to poll tendrl api

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/dashboard#467] opened 2017-06-23 20:09 UTC
When user logs out of the web interface, the ui continues to poll tendrl api. This doesn't make any sense, as at this point, no information can be fetched from the api until the user logs in again.

## Version

tendrl-dashboard-1.4.2-1.el7.centos.noarch

## Reproducer

1. Install Tendrl Server using tendrl-ansible
2. Log into Tendrl web interface and enable firebug console to watch http requests (using Firefox)
3. Log out and stay on the page
4. See firebug console

## Actual Results

There are errors (which fail on unsuccessful login) in the firebug console, as tendrl ui tries to fetch data without being logged in.

![todo-issue 004](https://user-images.githubusercontent.com/4759819/27498665-6d839d66-5860-11e7-9110-8e1849d4b368.png)

Call in question seems to be `notifications/`.

## Expected results

When user logs out, the ui stops any periodic requests to the api, so that there are no new http requests visible in the firebug console.

**Comment by gnehapk** [comment] 2017-06-24 04:29
Duplicate of #463. Hence closing it.

**Closed by gnehapk** 2017-06-24 04:29 UTC
