### ISSUE TITLE
Changes required for Edit pool.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/dashboard#218] opened 2017-04-04 12:43 UTC
As per the discussions on the Issue(https://github.com/Tendrl/dashboard/issues/175). The Pool name and Other parameters cannot be edited at the same time.

@julienlim  please go through the issue #175. We need to add one more value to kebab menu of pool list view and create a separate UI and UX for Edit Pool Name.

**Comment by julienlim** [comment] 2017-04-04 14:18
@cloudbehl I will comment directly on issue #175.

**Comment by nthomas-redhat** [comment] 2017-04-26 07:29
Duplicate of https://github.com/Tendrl/dashboard/issues/175

**Closed** 2017-05-29 10:27 UTC
Labels: duplicate
